/**
 * Generate configuration — a single-page large dialog.
 *
 * No more multi-step popups; all inputs live on one page:
 *  - the three parts (left rail / right rail / tie) come from: importing a .bbmodel from disk, or
 *    "Select a Tab" to extract the elements selected in an open tab; the right rail additionally
 *    offers "Mirror from First Model" — mirroring the left rail about its central YZ plane
 *    (mirrorPartYz).
 *  - gauge (px, with mm/inch conversion: pressing Enter in any field back-fills the other two) /
 *    track height / whole-model Y offset (px) / new workspace name.
 *  - portal textures: two independently optional imports — portal_track covers the track/ties
 *    (defaults to the parts' own textures), portal_track_mip generates the left/right overlay cubes
 *    teleport_left / teleport_right (wrapping each half of the ties, excluding the rails, textured
 *    with the mip; not generated by default); when both are absent teleport matches z_ortho /
 *    x_ortho. (See Create teleport.json)
 *  - the workspace format is decided by the input parts: any part with mesh groups → free model
 *    (format 'free'); otherwise Java block/item model.
 *
 * Parts are collected in the dialog **without** texture prefixes; generation applies scopeTextureKeys
 * prefixes (L / R / T) so the "source key → imported Texture" mapping stays globally unique.
 */

import type { DialogOptions } from 'blockbench-types/generated/interface/dialog';
import { allShapes } from '../logic/generator';
import { DEFAULT_GAUGE_PX, inchToPx, mmToPx, pxToInch, pxToMM } from '../logic/gauge';
import { consistentTextureSize, scopeTextureKeys, targetFormatForParts } from '../logic/parts';
import { mirrorPartYz } from '../logic/transform';
import { t } from '../i18n';
import type { PartModel, PortalConfig, ShapeSpec, SourceTexture, TrackConfig } from '../logic/types';
import { ProfileStore, type GenerateProfileValues } from '../logic/profile';
import { pickBbModels, parseImportedBbModel, extractSelectedPart, pickTabProject, pickPortalTrackTexture, pickPortalMipTexture } from './import';
import { blockbenchStorage, buildProfileWidget, type ProfileDriver } from './profile';
import { createTrackWorkspace } from '../build/workspace';

/** The final output of the dialog flow */
export interface GenerateOutput {
	config: TrackConfig;
	shapes: ShapeSpec[];
	/** Source texture key → Texture imported into the new workspace, for the assembly layer to apply */
	textureByKey: Map<string, Texture>;
}

type PartName = 'left' | 'right' | 'tie';

/**
 * Temporarily disables the "Select a Tab" part-import buttons (extract the elements selected in an open
 * tab). Set to true to restore the buttons. The pickTab action / extractSelectedPart code stays intact so
 * the feature can be re-enabled without touching anything else.
 */
const TAB_IMPORT_ENABLED = false;

/** Part selection state. Parts are the raw un-prefixed originals; prefixes are added uniformly at generation. */
interface PartState {
	left: PartModel | null;
	right: PartModel | null;
	tie: PartModel | null;
	/** Right rail source: none / file / selection / mirror (mirrored from the first model) */
	rightMode: 'none' | 'file' | 'selection' | 'mirror';
	/** portal_track texture (optional): covers the track/ties */
	portalTrack: SourceTexture | null;
	/** portal_track_mip texture (optional): textures the overlay cubes */
	portalMip: SourceTexture | null;
}

/** Part display name (i18n) */
function partLabel(which: PartName): string {
	return t('ctg.dialog.part.' + which);
}

/** Part source actions — used by button clicks and the test driver (see config._driver) */
interface PartActions {
	importPart(which: PartName): Promise<void>;
	/** Picks one of the currently open tabs and extracts its selected elements as the part */
	pickTab(which: PartName): Promise<void>;
	mirrorRight(): Promise<void>;
	importPortalTrack(): Promise<void>;
	importPortalMip(): Promise<void>;
}

/** Drives the dialog in smoke tests (not used directly by real Blockbench) */
interface ConfigDriver {
	actions: PartActions;
	getState(): PartState;
	/** Saved parameter-value batches (profiles); the part/texture source files are not included */
	profiles: ProfileDriver<GenerateProfileValues>;
}

// ── Dialog styles: two-column layout (left part sources + right config form) ──
const DIALOG_STYLE_ID = 'create-track-gen-dialog-styles';
const DIALOG_STYLE = `
/* Two columns: left part sources, right form parameters (lines and form.node are the two direct children of .dialog_content) */
#create-track-gen-dialog .dialog_content {
	display: grid;
	grid-template-columns: minmax(0, 1fr) minmax(0, 1fr);
	column-gap: 36px;
	row-gap: 4px;
	align-items: start;
}
/* Both grid children (left column container + right form.node) may shrink, so content can't overflow the columns */
#create-track-gen-dialog .dialog_content > * { min-width: 0; }
#create-track-gen-dialog .ctg-col { min-width: 0; }
#create-track-gen-dialog .ctg-col-title {
	font-weight: 700;
	font-size: 12px;
	text-transform: uppercase;
	letter-spacing: 0.05em;
	color: var(--color-subtle_text, #9a9a9a);
	margin: 2px 0 10px;
	padding-bottom: 6px;
	border-bottom: 1px solid var(--color-border, #3a3a3a);
}
#create-track-gen-dialog .ctg-part-row {
	margin: 6px 0 16px;
	padding: 10px 12px;
	border: 1px solid var(--color-border, #3a3a3a);
	border-radius: 6px;
}
#create-track-gen-dialog .ctg-part-title { font-weight: 600; margin-right: 8px; }
#create-track-gen-dialog .ctg-part-desc { color: var(--color-subtle_text, #8a8a8a); font-size: 12px; }
#create-track-gen-dialog .ctg-part-status { margin: 4px 0 8px; font-size: 12px; color: var(--color-subtle_text, #8a8a8a); min-height: 15px; }
#create-track-gen-dialog .ctg-part-status.ctg-status-ok { color: var(--active-color, #4caf50); }
#create-track-gen-dialog .ctg-part-actions { display: flex; gap: 6px; flex-wrap: wrap; }
#create-track-gen-dialog .ctg-btn {
	padding: 4px 12px;
	border: 1px solid var(--color-border, #555);
	border-radius: 4px;
	background: var(--color-button, #3f3f3f);
	color: var(--text-color, #eee);
	cursor: pointer;
	white-space: nowrap;
}
#create-track-gen-dialog .ctg-btn:hover { border-color: var(--active-color, #4caf50); color: var(--active-color, #4caf50); }
#create-track-gen-dialog .ctg-hint { font-size: 12px; color: var(--color-subtle_text, #8a8a8a); margin-top: 2px; line-height: 1.5; }
/* Profiles widget (saved parameter-value batches) */
#create-track-gen-dialog .ctg-profile {
	margin: 16px 0 0;
	padding: 10px 12px;
	border: 1px solid var(--color-border, #3a3a3a);
	border-radius: 6px;
}
#create-track-gen-dialog .ctg-profile-row {
	display: flex;
	gap: 6px;
	align-items: center;
	flex-wrap: wrap;
	margin-top: 6px;
}
#create-track-gen-dialog .ctg-profile-select,
#create-track-gen-dialog .ctg-profile-name {
	flex: 1;
	min-width: 0;
	box-sizing: border-box;
	background: var(--color-input, #202020);
	color: var(--text-color, #eee);
	border: 1px solid var(--color-border, #555);
	border-radius: 3px;
	padding: 0 10px;
	font: inherit;
}
/* 名称输入框：加高 + 显式行高，让下划线等下沉文字完整显示 */
#create-track-gen-dialog .ctg-profile-name {
	padding: 9px 10px;
	line-height: 1.5;
}
/* 原生下拉框：Chromium 里 line-height 会把选中文字往下推，改为固定高度让文字垂直居中 */
#create-track-gen-dialog .ctg-profile-select {
	height: 40px;
	line-height: normal;
}
/* Bottom buttons (OK / Cancel) pinned to the bottom-right */
#create-track-gen-dialog .dialog_bar.button_bar { text-align: right; }
`;

/** Injects the dialog styles (when a document exists; safely skipped in Node smoke tests) */
export function injectDialogStyles(): void {
	if (typeof document === 'undefined') return;
	if (document.getElementById(DIALOG_STYLE_ID)) return;
	const style = document.createElement('style');
	style.id = DIALOG_STYLE_ID;
	style.textContent = DIALOG_STYLE;
	document.head.appendChild(style);
}

export function disposeDialogStyles(): void {
	if (typeof document === 'undefined') return;
	document.getElementById(DIALOG_STYLE_ID)?.remove();
}

/** Creates a DOM element with a class name and text */
function el<K extends keyof HTMLElementTagNameMap>(tag: K, className?: string, text?: string): HTMLElementTagNameMap[K] {
	const node = document.createElement(tag);
	if (className) node.className = className;
	if (text !== undefined) node.textContent = text;
	return node;
}

/** A part source action button (which is not limited to PartName; 'portal' also goes through data-which) */
function partButton(act: string, which: string, label: string): HTMLButtonElement {
	const b = el('button', 'ctg-btn');
	b.type = 'button';
	b.dataset.act = act;
	b.dataset.which = which;
	b.textContent = label;
	return b;
}

/** Builds a single part row (DOM) */
function partRowEl(which: PartName): HTMLElement {
	const isRight = which === 'right';
	const row = el('div', 'ctg-part-row');
	row.dataset.part = which;
	const head = el('div', 'ctg-part-head');
	head.append(el('span', 'ctg-part-title', partLabel(which)));
	head.append(
		el(
			'span',
			'ctg-part-desc',
			isRight ? t('ctg.dialog.part.desc.right') : t('ctg.dialog.part.desc.left')
		)
	);
	row.append(head);
	const status = el('div', 'ctg-part-status', t('ctg.dialog.not_selected'));
	status.dataset.status = which;
	row.append(status);
	const actions = el('div', 'ctg-part-actions');
	actions.append(partButton('file', which, t('ctg.dialog.import_btn')));
	// "Select a Tab" import is temporarily disabled (see TAB_IMPORT_ENABLED); the handler stays wired
	// in case the flag is flipped back on.
	if (TAB_IMPORT_ENABLED) actions.append(partButton('tab', which, t('ctg.dialog.pick_tab_btn')));
	if (isRight) actions.append(partButton('mirror', which, t('ctg.dialog.mirror_btn')));
	row.append(actions);
	return row;
}

/**
 * Left column container: part sources (left rail / right rail / tie) + bottom hint.
 * A single HTMLElement is used as the lines entry (avoids Blockbench's deprecation warning for HTML
 * string lines), so .dialog_content has exactly two direct children: this column + the right
 * form.node, making the two columns sit side by side. Returns an empty string in Node smoke tests
 * (their Dialog stub doesn't render lines).
 */
function buildLeftColumn(): HTMLElement | '' {
	if (typeof document === 'undefined') return '';
	const col = el('div', 'ctg-col');
	col.append(el('div', 'ctg-col-title', t('ctg.dialog.col_parts')));
	col.append(partRowEl('left'));
	col.append(partRowEl('right'));
	col.append(partRowEl('tie'));
	// Portal textures: two independently optional imports
	const portalRow = el('div', 'ctg-part-row');
	portalRow.dataset.part = 'portal';
	const portalHead = el('div', 'ctg-part-head');
	portalHead.append(el('span', 'ctg-part-title', t('ctg.dialog.portal.title')));
	portalHead.append(el('span', 'ctg-part-desc', t('ctg.dialog.portal.desc')));
	portalRow.append(portalHead);
	const statusTrack = el('div', 'ctg-part-status', t('ctg.dialog.portal.track_default'));
	statusTrack.dataset.status = 'portal_track';
	portalRow.append(statusTrack);
	const statusMip = el('div', 'ctg-part-status', t('ctg.dialog.portal.mip_default'));
	statusMip.dataset.status = 'portal_mip';
	portalRow.append(statusMip);
	const portalActions = el('div', 'ctg-part-actions');
	portalActions.append(partButton('portal_track', 'portal', t('ctg.dialog.portal.import_track')));
	portalActions.append(partButton('portal_mip', 'portal', t('ctg.dialog.portal.import_mip')));
	portalRow.append(portalActions);
	col.append(portalRow);

	col.append(el('div', 'ctg-hint', t('ctg.dialog.hint')));
	return col;
}

/** A part / portal texture's status text and whether it's "ready" (OK styling) */
function statusInfo(state: PartState, which: PartName | 'portal_track' | 'portal_mip'): { text: string; ok: boolean } {
	if (which === 'portal_track') {
		return state.portalTrack
			? { text: t('ctg.dialog.portal.track_ok', state.portalTrack.name), ok: true }
			: { text: t('ctg.dialog.portal.track_default'), ok: false };
	}
	if (which === 'portal_mip') {
		return state.portalMip
			? { text: t('ctg.dialog.portal.mip_ok', state.portalMip.name), ok: true }
			: { text: t('ctg.dialog.portal.mip_default'), ok: false };
	}
	if (which === 'right' && state.rightMode === 'mirror') {
		return state.left
			? { text: t('ctg.dialog.mirror_status'), ok: true }
			: { text: t('ctg.dialog.need_left_short'), ok: false };
	}
	const part = which === 'left' ? state.left : which === 'tie' ? state.tie : state.right;
	if (!part) return { text: t('ctg.dialog.not_selected'), ok: false };
	const tex = part.textureSize ? t('ctg.dialog.tex_size', [part.textureSize[0], part.textureSize[1]]) : '';
	const count = part.cubes.length + (part.meshes?.length ?? 0);
	const meshNote = part.hasMesh ? t('ctg.dialog.mesh_note') : '';
	return { text: t('ctg.dialog.selected', [count, meshNote, tex]), ok: true };
}

/** Refreshes the part status rows */
function renderStatus(state: PartState, root: HTMLElement | null): void {
	if (!root) return;
	for (const which of ['left', 'right', 'tie', 'portal_track', 'portal_mip'] as (PartName | 'portal_track' | 'portal_mip')[]) {
		const el = root.querySelector(`[data-status="${which}"]`);
		if (!el) continue;
		const info = statusInfo(state, which);
		el.textContent = info.text;
		el.classList.toggle('ctg-status-ok', info.ok);
	}
}

/** Creates the part source actions (update state and trigger a status-row refresh) */
function createPartActions(state: PartState, onChange: () => void): PartActions {
	const setPart = (which: PartName, part: PartModel) => {
		if (which === 'left') state.left = part;
		else if (which === 'tie') state.tie = part;
		else {
			state.right = part;
			state.rightMode = part ? 'file' : 'none';
		}
		onChange();
	};

	return {
		async importPart(which) {
			const files = await pickBbModels();
			if (!files || files.length === 0) return;
			const file = files[0];
			try {
				const part = parseImportedBbModel(file);
				setPart(which, part);
				Blockbench.showQuickMessage(t('ctg.dialog.part_imported', [partLabel(which), file.name]));
			} catch (e: any) {
				Blockbench.showMessageBox({
					title: t('ctg.dialog.import_failed'),
					message: t('ctg.dialog.import_failed_msg', [file.name, e?.message ?? String(e)]),
					buttons: [t('ctg.ok')],
					confirm: 0,
				});
			}
		},
		async pickTab(which) {
			try {
				const proj = await pickTabProject();
				if (!proj) return;
				const part = extractSelectedPart(proj);
				setPart(which, part);
				const count = part.cubes.length + (part.meshes?.length ?? 0);
				Blockbench.showQuickMessage(
					t('ctg.dialog.part_extracted', [partLabel(which), (proj as any).name || t('ctg.dialog.unnamed'), count])
				);
			} catch (e: any) {
				Blockbench.showMessageBox({
					title: t('ctg.dialog.extract_failed'),
					message: e?.message ?? String(e),
					buttons: [t('ctg.ok')],
					confirm: 0,
				});
			}
		},
		async mirrorRight() {
			if (!state.left) {
				Blockbench.showMessageBox({
					title: t('ctg.dialog.need_left'),
					message: t('ctg.dialog.need_left_msg'),
					buttons: [t('ctg.ok')],
					confirm: 0,
				});
				return;
			}
			state.right = null;
			state.rightMode = 'mirror';
			onChange();
		},
		async importPortalTrack() {
			const tex = await pickPortalTrackTexture();
			if (!tex) {
				Blockbench.showQuickMessage(t('ctg.dialog.portal.track_not_imported'));
				return;
			}
			state.portalTrack = tex;
			onChange();
			Blockbench.showQuickMessage(t('ctg.dialog.portal.track_imported', tex.name));
		},
		async importPortalMip() {
			const tex = await pickPortalMipTexture();
			if (!tex) {
				Blockbench.showQuickMessage(t('ctg.dialog.portal.mip_not_imported'));
				return;
			}
			state.portalMip = tex;
			onChange();
			Blockbench.showQuickMessage(t('ctg.dialog.portal.mip_imported', tex.name));
		},
	};
}

/** Binds the part rows' buttons to the source actions */
function wireButtons(root: HTMLElement, actions: PartActions): void {
	root.querySelectorAll('button[data-act]').forEach((btn) => {
		btn.addEventListener('click', () => {
			const act = btn.getAttribute('data-act');
			const which = btn.getAttribute('data-which') as PartName;
			if (act === 'file') void actions.importPart(which);
			else if (act === 'tab') void actions.pickTab(which);
			else if (act === 'mirror') void actions.mirrorRight();
			else if (act === 'portal_track') void actions.importPortalTrack();
			else if (act === 'portal_mip') void actions.importPortalMip();
		});
	});
}

/** Display rounding: at most digits decimals with trailing zeros stripped (22.9600000 → 22.96) */
function roundDisplay(n: number, digits = 4): number {
	return Number(n.toFixed(digits));
}

/** The generate dialog's form config, keyed by form element id (each entry carries its current value) */
type GenerateForm = Record<string, { value: any }>;

/**
 * Reads the generate dialog's current parameter values (DOM inputs take precedence; falls back to the
 * form config defaults — the Node smoke-test path without a document).
 */
function readGenerateValues(form: GenerateForm, node: HTMLElement | null): GenerateProfileValues {
	const num = (id: string, fallback: number): number => {
		if (node) {
			const input = node.querySelector<HTMLInputElement>(`input#${id}`);
			if (input && input.value !== '') {
				const v = parseFloat(input.value);
				if (Number.isFinite(v)) return v;
			}
		}
		const def = Number(form[id]?.value);
		return Number.isFinite(def) ? def : fallback;
	};
	const text = (id: string, fallback: string): string => {
		const input = node?.querySelector<HTMLInputElement>(`input#${id}`);
		const v = input?.value.trim();
		return v ? v : (String(form[id]?.value ?? '') || fallback);
	};
	return {
		gauge: num('gauge', DEFAULT_GAUGE_PX),
		height: num('height', 0),
		yoffset: num('yoffset', 0),
		name: text('name', ''),
	};
}

/**
 * Applies profile values to the generate dialog (form config defaults + DOM inputs). The gauge is
 * stored in px; mm / inch are re-derived so all three fields stay consistent.
 */
function applyGenerateValues(form: GenerateForm, node: HTMLElement | null, values: GenerateProfileValues): void {
	form.gauge.value = values.gauge;
	form.gauge_mm.value = roundDisplay(pxToMM(values.gauge));
	form.gauge_inch.value = roundDisplay(pxToInch(values.gauge));
	form.height.value = values.height;
	form.yoffset.value = values.yoffset;
	form.name.value = values.name;
	if (node) {
		const set = (id: string, v: string | number): void => {
			const input = node.querySelector<HTMLInputElement>(`input#${id}`);
			if (input) input.value = String(v);
		};
		set('gauge', values.gauge);
		set('gauge_mm', roundDisplay(pxToMM(values.gauge)));
		set('gauge_inch', roundDisplay(pxToInch(values.gauge)));
		set('height', values.height);
		set('yoffset', values.yoffset);
		set('name', values.name);
	}
}

/**
 * Gauge three-field (px / mm / inch) cross-conversion: pressing Enter in any input uses that value as
 * the basis and auto-updates the other two (px is the basis used by generation). Blockbench number/text
 * form field input ids equal their form key (input#gauge etc.). Note the Enter propagation is stopped to
 * avoid triggering the dialog's default submit behavior.
 */
function wireGaugeConversion(root: HTMLElement): void {
	const pxEl = root.querySelector<HTMLInputElement>('input#gauge');
	const mmEl = root.querySelector<HTMLInputElement>('input#gauge_mm');
	const inchEl = root.querySelector<HTMLInputElement>('input#gauge_inch');
	if (!pxEl || !mmEl || !inchEl) return;

	// Convert from the current value of one input and back-fill the three fields
	const sync = (toPx: (v: number) => number, source: HTMLInputElement) => {
		const v = parseFloat(source.value);
		if (!Number.isFinite(v) || v <= 0) return;
		const px = toPx(v);
		pxEl.value = String(roundDisplay(px));
		mmEl.value = String(roundDisplay(pxToMM(px)));
		inchEl.value = String(roundDisplay(pxToInch(px)));
	};

	const bindEnter = (input: HTMLInputElement, toPx: (v: number) => number) => {
		input.addEventListener('keydown', (ev) => {
			if (ev.key !== 'Enter') return;
			sync(toPx, input);
			ev.preventDefault();
			ev.stopPropagation();
		});
	};

	bindEnter(pxEl, (v) => v);
	bindEnter(mmEl, (v) => mmToPx(v));
	bindEnter(inchEl, (v) => inchToPx(v));
}

/** Display text for a part's texture resolution */
function textureLabel(part: PartModel): string {
	if (!part.textureSize) return t('ctg.dialog.no_texture');
	return `${part.textureSize[0]} × ${part.textureSize[1]} px`;
}

/**
 * Builds the generation result from the dialog state + form values. The texture prefixes (L / R / T)
 * are applied to the three parts uniformly here; a mirrored right rail is derived with mirrorPartYz.
 * Returns { output } or { error } (the dialog stays open on error).
 */
function buildOutput(
	state: PartState,
	values: { gauge: number; height: number; yoffset: number; name: string }
): { output: GenerateOutput } | { error: string } {
	const { gauge, height, yoffset, name } = values;
	if (!state.left) return { error: t('ctg.error.need_left') };
	if (state.rightMode !== 'mirror' && !state.right) {
		return { error: t('ctg.error.need_right') };
	}
	if (!state.tie) return { error: t('ctg.error.need_tie') };
	if (!Number.isFinite(gauge) || gauge <= 0) return { error: t('ctg.error.gauge_positive') };
	if (!Number.isFinite(height) || height < 0) return { error: t('ctg.error.height_nonneg') };
	if (!Number.isFinite(yoffset)) return { error: t('ctg.error.yoffset_number') };
	if (!name) return { error: t('ctg.error.need_name') };

	// Right rail = mirror of the left about its central YZ plane (reuses the left's source textures,
	// only the sampling direction flips)
	const left = scopeTextureKeys(state.left, 'L');
	const right =
		state.rightMode === 'mirror'
			? scopeTextureKeys(mirrorPartYz(state.left), 'R')
			: scopeTextureKeys(state.right!, 'R');
	const tie = scopeTextureKeys(state.tie, 'T');

	// The three parts' texture resolutions must match, otherwise generation is rejected
	const textureSize = consistentTextureSize([left, right, tie]);
	if (!textureSize) {
		return {
			error: t('ctg.error.texture_mismatch', [textureLabel(left), textureLabel(right), textureLabel(tie)]),
		};
	}

	// Portal textures: each optional, prefixed 'P'; track covers the track/ties, mip textures the overlays
	const portalTextures: SourceTexture[] = [];
	const portal: PortalConfig = {};
	if (state.portalTrack) {
		const t = { ...state.portalTrack, key: 'P/track' };
		portalTextures.push(t);
		portal.trackTexture = t.key;
	}
	if (state.portalMip) {
		const t = { ...state.portalMip, key: 'P/mip' };
		portalTextures.push(t);
		portal.mipTexture = t.key;
		portal.mipTextureSize = [t.width, t.height];
	}

	const config: TrackConfig = { gaugePx: gauge, heightPx: height, wholeModelYOffset: yoffset, parts: { left, right, tie } };
	if (Object.keys(portal).length) config.portal = portal;
	const shapes = allShapes(config);
	try {
		const allTextures = [left, right, tie].flatMap((p) => p.textures ?? []).concat(portalTextures);
		// Workspace format: any part with mesh groups → free model (format 'free'); otherwise Java block/item model
		const targetFormat = targetFormatForParts([left, right, tie], (Project as any).format?.id);
		const textureByKey = createTrackWorkspace(targetFormat, name, textureSize, allTextures);
		return { output: { config, shapes, textureByKey } };
	} catch (e: any) {
		return { error: t('ctg.error.workspace_create', e?.message ?? String(e)) };
	}
}

/**
 * The full generation flow entry (single-page dialog). Returns the generation result, or null on
 * failure/cancel. Once the user fills all inputs and confirms, onConfirm creates the workspace and
 * resolves.
 */
export function runGenerateWizard(): Promise<GenerateOutput | null> {
	return new Promise((resolve) => {
		const state: PartState = { left: null, right: null, rightMode: 'none', tie: null, portalTrack: null, portalMip: null };
		let settled = false;
		const finish = (out: GenerateOutput | null) => {
			if (settled) return;
			settled = true;
			resolve(out);
		};

		let dialogNode: HTMLElement | null = null;
		const actions = createPartActions(state, () => renderStatus(state, dialogNode));
		// Saved parameter batches (profiles); persisted through Blockbench.storage
		const profileStore = new ProfileStore<GenerateProfileValues>(blockbenchStorage(), 'create_track_gen/generate_profiles');
		// The dialog's form config, read at call time (config is initialized by then)
		const form = (): GenerateForm => config.form as unknown as GenerateForm;

		const config = {
			id: 'create-track-gen-dialog',
			title: t('ctg.dialog.title'),
			icon: 'train',
			// 0.8× 视口宽度（Blockbench 对话框宽度是像素值；Node 冒烟测试无 window，回退固定宽度）
			width: Math.round((typeof window === 'undefined' ? 1400 : window.innerWidth) * 0.8),
			buttons: [t('ctg.ok'), t('ctg.cancel')],
			confirmIndex: 0,
			cancelIndex: 1,
			// lines first (left part column), form after (right params); .dialog_content uses grid for two columns
			part_order: ['lines', 'form'],
			lines: [buildLeftColumn()],
			form: {
				gauge: { label: t('ctg.form.gauge'), type: 'number', value: DEFAULT_GAUGE_PX, min: 0.1, step: 0.1, description: t('ctg.form.gauge.desc') },
				gauge_mm: { label: t('ctg.form.gauge_mm'), type: 'number', value: roundDisplay(pxToMM(DEFAULT_GAUGE_PX)), min: 0.1, step: 0.5, description: t('ctg.form.gauge_mm.desc') },
				gauge_inch: { label: t('ctg.form.gauge_inch'), type: 'number', value: roundDisplay(pxToInch(DEFAULT_GAUGE_PX)), min: 0.01, step: 0.1, description: t('ctg.form.gauge_inch.desc') },
				height: { label: t('ctg.form.height'), type: 'number', value: 2, min: 0, step: 0.5, description: t('ctg.form.height.desc') },
				yoffset: { label: t('ctg.form.yoffset'), type: 'number', value: 0, step: 0.5, description: t('ctg.form.yoffset.desc') },
				name: { label: t('ctg.form.name'), type: 'text', value: 'track', description: t('ctg.form.name.desc') },
			},
			onBuild(node?: HTMLElement) {
				if (!node) return;
				dialogNode = node;
				wireButtons(node, actions);
				wireGaugeConversion(node);
				renderStatus(state, node);
				// Right column = the Blockbench form node: a "Parameters" column title on top (matches
				// the "Track Parts" title of the left column) + the profiles widget at the bottom
				const formNode = node.querySelector<HTMLElement>('.dialog_content > .form');
				if (formNode) {
					formNode.prepend(el('div', 'ctg-col-title', t('ctg.dialog.col_parameters')));
					const widget = buildProfileWidget({
						list: () => profileStore.list(),
						apply: (name) => {
							const p = profileStore.find(name);
							if (p) applyGenerateValues(form(), dialogNode, p.values);
						},
						save: (name) => profileStore.put({ name, values: readGenerateValues(form(), dialogNode) }),
						remove: (name) => profileStore.remove(name),
					});
					if (widget) formNode.append(widget);
				}
			},
			onConfirm(formResult: any) {
				const result = buildOutput(state, {
					gauge: Number(formResult.gauge),
					height: Number(formResult.height),
					yoffset: Number(formResult.yoffset),
					name: String(formResult.name ?? '').trim(),
				});
				if ('error' in result) {
					Blockbench.showMessageBox({ title: t('ctg.form.config_error'), message: result.error, buttons: [t('ctg.ok')], confirm: 0 });
					return false; // keep the dialog open so the user can fix and retry
				}
				finish(result.output);
				return undefined; // allow the dialog to close
			},
			onCancel() {
				finish(null);
			},
			onClose() {
				finish(null);
			},
		} as DialogOptions & { _driver?: ConfigDriver };

		// Smoke-test hook: drives the part source actions + reads state directly (real Blockbench
		// doesn't depend on it)
		config._driver = {
			actions,
			getState: () => state,
			profiles: {
				list: () => profileStore.list(),
				save: (name) => profileStore.put({ name, values: readGenerateValues(form(), dialogNode) }),
				apply: (name) => {
					const p = profileStore.find(name);
					if (p) applyGenerateValues(form(), dialogNode, p.values);
				},
				remove: (name) => profileStore.remove(name),
			},
		};

		injectDialogStyles();
		const dialog = new Dialog(config);
		dialog.show();
	});
}
